spring:
  application:
    name: support-api
  datasource:
    url: jdbc:postgresql://localhost:5433/support_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      ticket-created: ticket.created
      ticket-processed: ticket.processed
    consumer:
      group-id: support-api-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
  resource:
    attributes:
      service.name: support-api

logging:
  level:
    root: INFO
    com.krish.supportapi: INFO
  pattern:
    console: '{"ts":"%d{yyyy-MM-dd HH:mm:ss.SSS}","lvl":"%p","svc":"support-api","trace":"%X{traceId:-}","span":"%X{spanId:-}","reqId":"%X{requestId:-}","method":"%X{method:-}","path":"%X{path:-}","log":"%logger{36}","msg":"%replace(%message){''\"'',''\\\"''}"}%n'

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry-ms: ${JWT_ACCESS_EXPIRY_MS:900000}
  refresh-token-expiry-ms: ${JWT_REFRESH_EXPIRY_MS:604800000}
